spring:
  profiles:
    active: default
  application:
      name: bainuo.proai.system
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
server:
    port: 9096
    ip: 192.168.3.21
#    ssl:
#       key-store: classpath:report.bainuogene.com.jks
#       key-store-password: 80287bkg0m345
#       keyStoreType: JKS
#       keyAlias: Tomcat
logging:
  config: classpath:logback-spring.xml
# 配置中心文件
  
